config/routes.rb
Rails.application.routes.draw do

  get "/", to: 'main#index', as: "root"
  post "/exec_query", to: "main#exec_query"
  post "/get_history", to: "main#get_history"

  # You can have the root of your site routed with "root"
  resources :churches, only: [:index, :show]


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/church.rb
class Church < ActiveRecord::Base
	has_many :church_data, -> { order(year: :asc) }, class_name: ChurchData 
end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController
	def index
		@churches = Church.all.order(:name)
	end

	def show
		@church = Church.find(params[:id])
	end
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/views/churches/index.html.erb
<h1>Church List</h1>

<table>
	<tr><th>Name</th> <th>ID</th> <th>District</th> <th>City</th> <th>State</th></tr>
	<% @churches.each do |church| %>
		<tr>
			<td> <%= link_to church.name, church_path(church) %></td> 
			<%= "<td>#{church.id}</td>".html_safe %>
			<%= "<td>#{church.district}</td>".html_safe %>
			<%= "<td>#{church.city}</td>".html_safe %>
			<%= "<td>#{church.state}</td>".html_safe %>
		</tr>
	<% end %>
</table>

app/views/churches/show.html.erb
<h1><%= "#{@church.name} (#{@church.id})" %></h1>

<table>
	<th class="first-col"></th>
	<% (2000..2014).each do |year| %>
		<th class="year-col"><%= year %></th>
	<% end %>

	<% data = @church.church_data.to_a %>
	<% ChurchData.get_prop_tree().each do |category| %>
		<tr><td class="category"><strong><%= category[:descriptor] %></td></strong>
		<% (2000..2014).each do |year| %>
			<td class="category"></td>
		<% end %>
		</tr>
		<% category[:children].each do |row| %>
			<tr class="item"><td><%= row[:descriptor] %></td>
			<% (2000..2014).each do |year| %>
				<% i = year - 2000 %>
				<% next if (row[:value].nil? or data.length <= i) %>
				<td><%= data[i].send row[:value] %></td>
			<% end %>
		<% end %>
		<tr><td>&nbsp;</td></tr>
	<% end %>
</table>

<%= link_to "Back", churches_path %>